version: '3.7'

services: 
  #   Backend build commented out on request to make the project front-end only

  # backend:
  #   build: ./my-timers-backend
  #   ports: 
  #     - 8000:8000
  #   depends_on:
  #     - mongodb
  #   links:
  #     - mongodb

  frontend:
    build: ./my-timers-frontend
    ports: 
      - 8080:8080

  # Database build commented out on request to make the project front-end only

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - data:/data/db

volumes: 
  data: