version: '3.7'

services: 
  backend:
    build: ./my-timers-backend
    ports: 
      - 8000:8000
    depends_on:
      - mongodb
    links:
      - mongodb

  frontend:
    build: ./my-timers-frontend
    ports: 
      - 8080:8080

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db



volumes: 
  data: